---

# Allow control node physical hosts to contact metadata endpoint
# since the Neutron agents are no longer containerized.
haproxy_metal_networks:
  - "{{ cidr_networks.external }}"
haproxy_nova_metadata_whitelist_networks: "{{ haproxy_whitelist_networks +
                                              haproxy_metal_networks }}"
